# @package hydra.launcher

_target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher

submitit_folder: ${hydra.sweep.dir}/.submitit/%j
timeout_min: 7200
cpus_per_task: 16
gpus_per_node: ${gpus}
tasks_per_node: 1
mem_gb: 120
nodes: 1
name: ${hydra.job.name}
partition: gpu
comment: null
constraint: null
exclude: null
signal_delay_s: 120
max_num_timeout: 0
array_parallelism: 16
