from .xvector import XvectorSpeakerRecognitionModule, XvectorConfig
from .ecapa import EcapaTdnnSpeakerRecognitionModule, EcapaTdnnConfig
from .wav2vec2 import Wav2vec2SpeakerRecognitionModule, Wav2vec2Config
